#!/bin/bash

### You can change some default settings down here if you want to

# Default music directory.
MUSIC_DIR=~/Music

# Output mp3 bitrate (kbps)
BITRATE=320

### ------------------------------------------------------------

print_help () {
	echo 'USAGE: rip-ninja [name-of-the-album]'
}

overwrite_prompt () {
	echo -e "Warning! It seems that $1 already exists in the $MUSIC_DIR directory.\nOverwrite files? (y/n)"
	read user_input

	if [ "$user_input" != "y" ] && [ "$user_input" != "Y" ]
	then
		echo "Aborted."
		exit 1
	fi
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] 
then
	print_help
	exit 0
fi

if [ -z "$1" ]
then
	echo "Please give the name of the album."
	print_help
	exit 1
fi

if [ -n "$2" ]
then
	echo "Too many arguments."
	print_help
	exit 1
fi

# Going into default music directory
cd $MUSIC_DIR || echo "$MUSIC_DIR does not exist!" $$ exit 1

# Creating file directories
mkdir $MUSIC_DIR/wav/$1 || overwrite_prompt $1
mkdir $MUSIC_DIR/mp3/$1

# Ripping cd into wave files
cd $MUSIC_DIR/wav/$1
cdparanoia -B

# Converting ripped wave files into mp3s
for track in *;
do
	lame -b $BITRATE $track --out-dir $MUSIC_DIR/mp3/$1
done
