#!/bin/sh

### ------------------------------------------------------------
### Functions
### ------------------------------------------------------------

print_help () {
    echo 'USAGE: rip-ninja [OUTPUT_AUDIO_FORMAT] [OUTPUT_DIRECTORY_PATH]'
}

overwrite_prompt () {
	echo -e "Warning! It seems that $1 already exists.\nOverwrite files? (y/N)"
	read user_input

	if [ "$user_input" != "y" ] && [ "$user_input" != "Y" ]
	then
		echo "Aborted."
		exit 1
	fi
}

### ------------------------------------------------------------
### Scirpt arguments parsing
### ------------------------------------------------------------

# Help me!
if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "help" ] 
then
	print_help
	exit 0
fi

# Too many arguments
if [ $3 ]
then
	echo "Too many arguments."
	print_help
	exit 1
fi

# Output audio format
if [ -z $1 ] || [ $1 = 'wav' ]
then
    OUTPUT_AUDIO_FORMAT=""
else
    OUTPUT_AUDIO_FORMAT=$1
fi

# Output directory path
if [ "$2" ]
then
    [ -d "$2" ] || mkdir "$2" || overwrite_prompt "$2"
    cd "$2"
fi

### ------------------------------------------------------------
### Actual ripping audio part (let's goooooooooo)
### ------------------------------------------------------------

# Ripping cd into wave files
cdparanoia -B

# Converting ripped wave files into flacs
if [ $OUTPUT_AUDIO_FORMAT ]
then
    for track in *.wav;
    do
        ffmpeg -i $track $track.$OUTPUT_AUDIO_FORMAT
        rm $track
    done
fi
