#!/bin/bash

### You can change some default settings down here if you want to

# Default directories (!!! It is important that WAVE and FLAC directories are separate. Otherwise rip-ninja might not function properly !!!)

MUSIC_DIR=~/Music
WAVE_DIR=$MUSIC_DIR/wav
FLAC_DIR=$MUSIC_DIR/flac

### ------------------------------------------------------------

print_help () {
	echo 'USAGE: rip-ninja [name-of-the-album]'
}

overwrite_prompt () {
	echo -e "Warning! It seems that $1 already exists in the $MUSIC_DIR directory.\nOverwrite files? (y/n)"
	read user_input

	if [ "$user_input" != "y" ] && [ "$user_input" != "Y" ]
	then
		echo "Aborted."
		exit 1
	fi
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] 
then
	print_help
	exit 0
fi

if [ -z "$1" ]
then
	echo "Please give the name of the album."
	print_help
	exit 1
fi

if [ -n "$2" ]
then
	echo "Too many arguments."
	print_help
	exit 1
fi

# Creating tracks directories if they don't exist
[ -d $MUSIC_DIR ] || mkdir $MUSIC_DIR
[ -d $WAVE_DIR ]  || mkdir $WAVE_DIR
[ -d $FLAC_DIR ]  || mkdir $FLAC_DIR

mkdir $WAVE_DIR/$1 || overwrite_prompt $1
mkdir $FLAC_DIR/$1

# Ripping cd into wave files
cd $WAVE_DIR/$1
cdparanoia -B

# Converting ripped wave files into flacs
for track in *;
do
	ffmpeg -i $track $FLAC_DIR/$1/$track.flac
done
