#!/bin/bash

### You can change some default settings down here if you want to

# Default audio splice duration in seconds (for AudD recognition API)
SPLICE_DURATION=10

### ------------------------------------------------------------

print_help () {
	echo 'USAGE: tag-ninja [path_to_audio_file]'
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] 
then
	print_help
	exit 0
fi

if [ -z "$1" ]
then
	echo "Please give the path to the audio file you want to tag."
	print_help
	exit 1
fi

if [ -n "$2" ]
then
	echo "Too many arguments."
	print_help
	exit 1
fi


# Checking if given file exists 
if [ ! -f $1 ]
then
	echo "File does not exist."
	exit 1
fi

# Creating path a temporary file
AUDIO_SPLICE_FLAC=$(mktemp /tmp/tag-ninja-XXXXXXXX.flac)

# Splicing audio file
ffmpeg -hide_banner -loglevel panic -y -ss 0 -i $1 -t $SPLICE_DURATION -c copy $AUDIO_SPLICE_FLAC

# Requesting song recognition from AudD
curl -X POST -F "api_token=$(cat api_token)" -F "file=@$AUDIO_SPLICE_FLAC" -F "return=spotify" https://api.audd.io/

# rm -f /tmp/tag-ninja* 
exit 0
